=== paradox9133/SOA/src/resources/xml/KatalogSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Katalog">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="wieza" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
				<xs:sequence>
				  	<xs:element name="mag" minOccurs="0" maxOccurs="unbounded">
				  		<xs:complexType>
				  			<xs:attribute name="imie" type="xs:string"></xs:attribute>
				  			<xs:attribute name="moc" type="xs:int"></xs:attribute>
				  			<xs:attribute name="krag" type="kragType"></xs:attribute>
				  		</xs:complexType>
					  </xs:element>
				</xs:sequence>
				<xs:attribute name="wysokosc" type="xs:int"></xs:attribute>
		  	</xs:complexType>
			</xs:element>

		</xs:sequence>
	</xs:complexType>
</xs:element>


<xs:simpleType name="kragType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="ogien" />
    <xs:enumeration value="woda" />
    <xs:enumeration value="ziemia" />
    <xs:enumeration value="powierze" />
  </xs:restriction>
</xs:simpleType>



</xs:schema>

=== paradox9133/SOA/src/resources/xml/Katalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<Katalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="KatalogSchema.xsd">
  <wieza wysokosc="20">
    <mag imie="Jan" krag="powierze" moc="2000"/>
    <mag imie="Benek" krag="powierze" moc="100"/>
  </wieza>
  <wieza wysokosc="24">
  	<mag imie="Tomek" krag="ogien" moc="500"/>
  	<mag imie="Kuba" krag="powierze" moc="500"/>
  	<mag imie="Adam" krag="ziemia" moc="5000"/>
  </wieza>
</Katalog>
